# Generated by Django 4.2.10 on 2024-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0002_alter_profile_facebook_alter_profile_github_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('set_published_status', 'Can set the status of the resume to either publish or not')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
